export const actionDisplayNames = new Map([
  ["toggleMainDeckView", "Toggle Main Deck View"],
  ["toggleExtraDeckView", "Toggle Extra Deck View"],
  ["toggleGraveView", "Toggle GY View"],
  ["toggleBanishView", "Toggle Banished View"],
  ["activateCard", 'Activate Card - "To S/T"'],
  ["banishCard", "Banish Card"],
  ["banishCardFd", "Banish Card Face-Down"],
  ["banishDeckTop", "Banish Top of Main Deck"],
  ["banishDeckTopFd", "Banish Top of Main Deck Face-Down"],
  ["declareEff", "Declare"],
  ["normalSummonCard", "Normal Summon"],
  ["overlayMaterial", "Overlay"],
  ["specSummonAtk", "Special Summon (ATK)"],
  ["specSummonDef", "Special Summon (DEF)"],
  ["xyzSummonAtk", "XYZ Summon (ATK)"],
  ["xyzSummonDef", "XYZ Summon (DEF)"],
  ["setCard", "Set Card"],
  ["cardToDeckBottom", "To Bottom of Deck"],
  ["cardToGy", "To Graveyard"],
  ["bounceCard", "Add Card to Hand/Extra Deck"],
  ["cardToExtraDeckFu", "Add Card to Extra Deck Face-Up"],
  ["addLp", "Gain LP"],
  ["subLp", "Lose LP"],
  ["toggleChatBox", "Toggle Chat Box"],
  ["signalThinking", "Thinking"],
  ["singalOkay", "Thumbs Up"],
]);
